### ISSUE TITLE
Include documentation on how to use this library in our app's tests without hitting the mailchimp API.

### ISSUE THREAD

**Issue by lpil** [discopatrick/mailchimpy#1]
Is there a test mode?

**Comment by discopatrick** [comment]
Yes, betamax is now integrated. Please see https://github.com/discopatrick/mailchimpy#tests


> On the first test run, all tests will need to make real calls to the API over the internet. Subsequent test runs will use the betamax recordings, and will be much quicker.

**Comment by lpil** [comment]
Not in the tests for this library, in tests for applications using this library. There should be a nice way of using the library in tests, otherwise it's not a very useful library IMO.

**Comment by discopatrick** [comment]
Ah, understood. This should also be possible with betamax. I'll have a think about I can make this happen. Thanks for the feedback.

**Comment by discopatrick** [comment]
On further thought, this doesn't require betamax at all. We don't need to record and play back any http interactions here. We just need the library to return dummy values instead of hitting the API.

**Comment by lpil** [comment]
That's the one! We can also expose an array of sent emails that can be checked in tests.
